### ISSUE TITLE
addSelectVisChooser does not respect initialVis

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/caleydo.github.io#100]
In http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?2 (code-2.js) an initialVis has been specified, and addSelectVisChooser adds a list of visualizations for the user to choose from, but the initial state of the select does not match what initialVis specifies. Am I doing something wrong, or is there a bug?

**Comment by thinkh** [comment]
That was a bug that I fixed. Note, that you can hand a list of forms to `addSelectVisChooser()`, but only the selection of the first form will set the selectedIndex.

**Comment by mccalluc** [comment]
Sorry if I'm misunderstanding something. I would assume your bug fix is in the v0.0.1 build, but I still see this behavior at this moment on http://www.caleydo.org/documentation/tutorial/web_bundle/frame.html?2 ... or is the problem in my tutorial code? Sorry for not getting it.

**Comment by thinkh** [comment]
You're right: I fixed the bug, but I didn't build the library again (hence, it's not deployed anywhere).

@mccalluc: Could you increment the version number to 0.0.2 and build a new library version? Then we should both know what files we are working with.

**Comment by thinkh** [comment]
I updated the [bundle_lib readme](https://github.com/Caleydo/bundle_lib) about a paragraph how to build the library. Don't forget to update the version number in the package.json before. ;-)

**Comment by thinkh** [comment]
I updated the library files on S3 and now it's fixed.
